-- MySQL Script generated by MySQL Workbench
-- Wed Apr 29 10:37:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moocdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `moocdb` ;

-- -----------------------------------------------------
-- Schema moocdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moocdb` DEFAULT CHARACTER SET utf8 ;
USE `moocdb` ;

-- -----------------------------------------------------
-- Table `moocdb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`course` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '课程名称',
  `summary` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '课程简介',
  `description` TEXT NULL DEFAULT NULL COMMENT '课程详细介绍',
  `tag_ids` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '标签IDs',
  `period` INT(10) NOT NULL DEFAULT '0' COMMENT '课程周期',
  `price` INT(10) NOT NULL DEFAULT '0' COMMENT '课程售价(元)',
  `seq` INT(10) NOT NULL DEFAULT '0' COMMENT '排序值',
  `start_article_id` INT NULL COMMENT '起始文章ID',
  `creator_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建者ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '课程表';


-- -----------------------------------------------------
-- Table `moocdb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`article` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '节名称',
  `period` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '课程周期',
  `course_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '课程ID',
  `style` ENUM('markdown', 'richtext', 'text') NOT NULL DEFAULT 'markdown' COMMENT '内容格式',
  `html` MEDIUMTEXT NULL DEFAULT NULL COMMENT '内容HTML缓存',
  `content` MEDIUMTEXT NULL DEFAULT NULL COMMENT '节内容',
  `seq` INT(10) NOT NULL DEFAULT '0',
  `level` INT NULL DEFAULT 1 COMMENT '层级',
  `creator_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建者ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `parent_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '父ID',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '课程文章表';


-- -----------------------------------------------------
-- Table `moocdb`.`clazz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`clazz` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '班级名称',
  `start_date` DATE NULL DEFAULT NULL COMMENT '开始日期',
  `end_date` DATE NULL DEFAULT NULL COMMENT '结束日期',
  `master_name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '班主任姓名',
  `master_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '班主任用户ID',
  `creator_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建者ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '班级表';


-- -----------------------------------------------------
-- Table `moocdb`.`clazz_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`clazz_member` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID',
  `clazz_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '班级ID',
  `join_date` DATE NULL DEFAULT NULL COMMENT '加入日期',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '班级成员表';


-- -----------------------------------------------------
-- Table `moocdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '手机号码',
  `username` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '用户名',
  `email` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '邮箱',
  `password` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码',
  `full_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '姓名',
  `roles` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '角色编码',
  `avatar` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '默认头像',
  `homepage` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '个人主页',
  `gender` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '性别:0-未知;1-男;2-女;3-保密;',
  `birthday` DATE NULL DEFAULT NULL COMMENT '生日',
  `wx_unique_id` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '微信 UNIQUE ID',
  `wx_openid` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '微信 OPEN ID',
  `wx_sex` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '微信性别',
  `wx_city` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '微信所在城市',
  `wx_province` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '微信所在省份',
  `wx_country` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '微信所在国家',
  `register_ip` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '注册IP',
  `last_visited` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后在线时间',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `job_title` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '职称',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `moocdb`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`collection` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID',
  `obj_type` ENUM('course', 'paper', 'question', 'feed') NOT NULL DEFAULT 'feed' COMMENT '类型',
  `obj_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '收藏对象ID',
  `memo` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '收藏表';


-- -----------------------------------------------------
-- Table `moocdb`.`paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`paper` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '试卷名称',
  `content` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '试卷说明',
  `tag_ids` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '标签IDs',
  `mode` ENUM('exercise', 'exam') NOT NULL DEFAULT 'exercise' COMMENT '试卷模式',
  `is_survey` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否调查',
  `is_official` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '来源官方吗',
  `is_draft` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '是否草稿',
  `passed_score` INT(10) NOT NULL DEFAULT '0' COMMENT '通过分数',
  `score` INT(10) NOT NULL DEFAULT '0' COMMENT '试卷分数',
  `subjective` INT(10) NOT NULL DEFAULT '0' COMMENT '主观题数量',
  `objective` INT(10) NOT NULL DEFAULT '0' COMMENT '客观题数量',
  `questions` INT(10) NOT NULL DEFAULT '0' COMMENT '题目数量',
  `difficulty` INT(10) NOT NULL DEFAULT '0' COMMENT '试卷难度',
  `minutes_limited` INT(10) NOT NULL DEFAULT '0' COMMENT '做题时间限制',
  `creator_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建者用户ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '试卷表';


-- -----------------------------------------------------
-- Table `moocdb`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`quiz` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `paper_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '试卷ID',
  `min_score` INT(10) NOT NULL DEFAULT '0' COMMENT '最小分数',
  `max_score` INT(10) NOT NULL DEFAULT '0' COMMENT '最大分数',
  `evaluation` TEXT NULL DEFAULT NULL COMMENT '评价',
  `creator_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建者用户ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '试卷评价表';


-- -----------------------------------------------------
-- Table `moocdb`.`quiz_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`quiz_result` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `paper_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '试卷ID',
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '答题用户ID',
  `score` INT(10) NOT NULL DEFAULT '0' COMMENT '得分',
  `correct_num` INT(10) NOT NULL DEFAULT '0' COMMENT '正确的数量(客观题)',
  `duration` INT(10) NOT NULL DEFAULT '0' COMMENT '做题时间(单位:秒)',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `quiz_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '试卷结果表';


-- -----------------------------------------------------
-- Table `moocdb`.`quiz_result_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`quiz_result_item` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `paper_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '试卷ID，如果为0，则为随机答题',
  `quiz_result_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '试卷记录ID，如果为0，则为随机答题',
  `question_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '题目ID',
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '答题用户ID',
  `score` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '测验得分',
  `duration` INT(10) NOT NULL DEFAULT '0' COMMENT '做题时间(单位:秒)',
  `success` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '是否答对',
  `answer` TEXT NULL DEFAULT NULL COMMENT '用户答案',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lang` ENUM('c', 'java', 'js') NOT NULL DEFAULT 'java' COMMENT '编程题语言类型',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '答题记录表';


-- -----------------------------------------------------
-- Table `moocdb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`comment` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `obj_type` ENUM('feed', 'question', 'article', 'quiz_result_item') NOT NULL DEFAULT 'feed' COMMENT '评论类型',
  `obj_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '评论对象ID',
  `style` ENUM('text', 'richtext', 'markdown') NOT NULL DEFAULT 'text' COMMENT '内容渲染样式',
  `content` TEXT NULL DEFAULT NULL COMMENT '评论内容',
  `img_urls` TEXT NULL DEFAULT NULL COMMENT '图片URL，多个图片用英文逗号隔开',
  `creator_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建者用户ID',
  `receiver_id` INT(10) NOT NULL DEFAULT '0' COMMENT '被回复者用户ID',
  `client_ip` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '客户端IP',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '评论表';


-- -----------------------------------------------------
-- Table `moocdb`.`feed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`feed` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` INT(10) NOT NULL DEFAULT '0' COMMENT '类型:1-默认类型;2-留言咨询;',
  `show_type` INT(10) NOT NULL DEFAULT '0' COMMENT '展示方案:1-完全公开;2-仅群组内公开;',
  `title` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '标题',
  `style` ENUM('text', 'richtext', 'markdown') NOT NULL DEFAULT 'text' COMMENT '内容渲染样式',
  `content` MEDIUMTEXT NULL DEFAULT NULL COMMENT '内容',
  `img_urls` TEXT NULL DEFAULT NULL COMMENT '图片链接,多个用英文逗号隔开',
  `file_urls` TEXT NULL DEFAULT NULL COMMENT '文件链接,多个用英文逗号隔开',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
  `views` INT(10) NOT NULL DEFAULT '0' COMMENT '浏览量',
  `client_ip` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '发布者客户端IP',
  `group_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '所属群组ID',
  `creator_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建者用户ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Feed表';


-- -----------------------------------------------------
-- Table `moocdb`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`groups` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '群组名称',
  `avatar` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '群组头像',
  `intro` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '群组说明',
  `type` TINYINT(2) NOT NULL DEFAULT '1' COMMENT '群组类型:1-公开群组;2-私密群组;',
  `creator_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建者ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '群组表';


-- -----------------------------------------------------
-- Table `moocdb`.`group_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`group_member` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '群组ID',
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '成员在群内的名称',
  `is_receive` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '是否接收消息',
  `role_type` MEDIUMINT(2) NOT NULL DEFAULT '1' COMMENT '群角色:1-成员;2-管理员;3-群主;',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '群组成员表';


-- -----------------------------------------------------
-- Table `moocdb`.`group_subscriber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`group_subscriber` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '群组ID(被订阅)',
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID(订阅)',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否已删除',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '群组订阅表';


-- -----------------------------------------------------
-- Table `moocdb`.`keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`keyword` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '搜索关键词',
  `memo` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
  `hot` INT(10) NOT NULL DEFAULT '0' COMMENT '热度(运营干预)',
  `hits` INT(10) NOT NULL DEFAULT '0' COMMENT '命中次数',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '搜索热词表';


-- -----------------------------------------------------
-- Table `moocdb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`message` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sender_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '发送者ID',
  `receiver_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '接受者ID',
  `sender_name` VARCHAR(128) NOT NULL DEFAULT '0' COMMENT '发送者名称',
  `receiver_name` VARCHAR(128) NOT NULL DEFAULT '0' COMMENT '接受者名称',
  `content` VARCHAR(500) NOT NULL DEFAULT '0' COMMENT '消息内容',
  `type` INT(10) NOT NULL DEFAULT '0' COMMENT '消息类型:1-默认;',
  `obj_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '关联对象ID',
  `struct` VARCHAR(500) NOT NULL DEFAULT '0' COMMENT '消息额外JSON信息',
  `has_read` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否已读',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '消息表';


-- -----------------------------------------------------
-- Table `moocdb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`orders` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID',
  `type` ENUM('course', 'clazz') NOT NULL DEFAULT 'course' COMMENT '订单类型',
  `amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单总金额',
  `actual_amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单实际支付金额',
  `payment_channel` INT(10) NOT NULL DEFAULT '0' COMMENT '订单支付渠道',
  `memo` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '用户订单表';


-- -----------------------------------------------------
-- Table `moocdb`.`orders_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`orders_item` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('course', 'clazz') NOT NULL DEFAULT 'course' COMMENT '订单类型',
  `obj_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '产品ID',
  `obj_name` VARCHAR(200) NOT NULL DEFAULT '0' COMMENT '产品名称',
  `orders_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单ID',
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID',
  `subtotal` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '条目金额',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '订单产品表';


-- -----------------------------------------------------
-- Table `moocdb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`question` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '题目名称',
  `tag_ids` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '标签IDs',
  `content_is_md` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'content是否Markdown',
  `content` TEXT NULL DEFAULT NULL COMMENT '题目描述',
  `is_survey` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否调查',
  `type` ENUM('choice', 'multi_choice', 'qa', 'code') NOT NULL DEFAULT 'choice' COMMENT '题目类型',
  `answer_is_md` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'answer是否Markdown',
  `answer` TEXT NULL DEFAULT NULL COMMENT '答案',
  `difficulty` INT(10) NOT NULL DEFAULT '0' COMMENT '难度',
  `score` INT(10) NOT NULL DEFAULT '0' COMMENT '默认分数',
  `hots` INT(10) NOT NULL DEFAULT '0' COMMENT '热度指数',
  `complexity_time` INT(10) NOT NULL DEFAULT '0' COMMENT '运行时间限制,单位秒',
  `complexity_space` INT(10) NOT NULL DEFAULT '0' COMMENT '运行空间限制,单位KB',
  `input` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '输入',
  `output` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '输出',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `course_id` INT(10) NOT NULL DEFAULT '0',
  `chapter_id` INT(10) NOT NULL DEFAULT '0',
  `article_id` INT(10) NOT NULL DEFAULT '0',
  `enable` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '题目表';


-- -----------------------------------------------------
-- Table `moocdb`.`paper_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`paper_item` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `seq` INT(10) NOT NULL DEFAULT '0' COMMENT '排序',
  `paper_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '试卷ID',
  `question_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '试题ID',
  `score` INT(10) NOT NULL DEFAULT '0' COMMENT '分数',
  `rate` DECIMAL(10,2) NOT NULL DEFAULT '1.00' COMMENT '比例',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '试卷试题表';


-- -----------------------------------------------------
-- Table `moocdb`.`question_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`question_option` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '试题ID',
  `no` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '选项编号',
  `lang` ENUM('java', 'c', 'js') NOT NULL DEFAULT 'java' COMMENT '代码语言',
  `content_is_md` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'content是否Markdown',
  `content` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '选项内容/代码模板',
  `answer_is_md` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'answer是否Markdown',
  `answer` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '选项解析/答案代码',
  `score` INT(10) NOT NULL DEFAULT '0' COMMENT '分数',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '题目选项/模板表';


-- -----------------------------------------------------
-- Table `moocdb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`role` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '角色编码',
  `name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '角色名称',
  `config` MEDIUMTEXT NULL DEFAULT NULL COMMENT '角色相关权限配置, JSON字符串',
  `memo` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `idx_code` (`code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `moocdb`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`tag` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '标签英文Code',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '标签名称',
  `type` ENUM('course', 'paper', 'question', 'feed') NOT NULL DEFAULT 'feed' COMMENT '标签类型',
  `memo` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '标签备注',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '标签表';


-- -----------------------------------------------------
-- Table `moocdb`.`tag_cached`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`tag_cached` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `obj_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '对象ID',
  `tag_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '标签ID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '试题标签关系表';


-- -----------------------------------------------------
-- Table `moocdb`.`user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`user_profile` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID',
  `full_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '姓名',
  `avatar` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '默认头像',
  `homepage` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '个人主页',
  `github` VARCHAR(300) NOT NULL DEFAULT '' COMMENT 'GiHub主页',
  `gender` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '性别:0-未知;1-男;2-女;3-保密;',
  `birthday` DATE NULL DEFAULT NULL COMMENT '生日',
  `birth_year` INT(10) NOT NULL DEFAULT '0' COMMENT '出生年份',
  `birth_month` INT(10) NOT NULL DEFAULT '0' COMMENT '出生月份',
  `working_status` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '工作状态',
  `expect_city` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '期望工作城市',
  `expect_salary` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '期望薪资',
  `phone` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '手机号码',
  `email` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '电子邮箱',
  `intro` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '个人简介',
  `school` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '学校',
  `major` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '专业',
  `admission_year` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '入学年份',
  `graduation_year` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '毕业年份',
  `english_ability` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '英语能力',
  `work_experience` TEXT NULL DEFAULT NULL COMMENT '工作经历',
  `project_experience` TEXT NULL DEFAULT NULL COMMENT '项目经验',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `education` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '学历',
  `birthplace` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '籍贯',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '用户档案表';


-- -----------------------------------------------------
-- Table `moocdb`.`user_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moocdb`.`user_file` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '远程链接',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '文件名',
  `origin_name` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '原始文件名',
  `description` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '图片/文件描述',
  `user_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID',
  `obj_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '关联对象ID',
  `obj_type` ENUM('default', 'course', 'article', 'paper', 'question', 'feed') NOT NULL DEFAULT 'feed' COMMENT '关联对象类型',
  `type` ENUM('img', 'file') NOT NULL DEFAULT 'img' COMMENT '文件类型',
  `size` INT(11) NOT NULL DEFAULT '0' COMMENT '文件大小(单位Byte)',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '用户上传文件表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
